

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzYW50aW5vIiwicm9sZSI6InNlY3JldGFyeSIsImlhdCI6MTc0NTYxMDk5OSwiZXhwIjoxNzQ1NjE0NTk5fQ.1naV_m6524YG3IWMPsPOz0WlpWmH7ED9cU5jZ2tS9x4

### Pruebas de validación

### Falta campos obligatorios (debería fallar)
POST http://localhost:3000/api/attention
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2023-12-01"
}

### Fecha en pasado (debería fallar)
POST http://localhost:3000/api/attention
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2020-01-01",
  "consultationHours": 1,
  "patient": 1
}

### Horario consulta inexistente (debería fallar)
POST http://localhost:3000/api/attention
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-12-01",
  "consultationHours": 999,
  "patient": 1
}

### Paciente inexistente (debería fallar)
POST http://localhost:3000/api/attention
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-12-01T10:00:00",
  "consultationHours": 1,
  "patient": 999,
  "reason": "Control anual"
}


### Creación válida (éxito)
# @name createAttention
POST http://localhost:3000/api/attention
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-12-01T10:00:00",
  "consultationHours": 1,
  "patient": 2,
  "reason": "Control anual"
}

### Misma fecha y misma hora (debería fallar)
POST http://localhost:3000/api/attention
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-12-01T10:00:00",
  "consultationHours": 1,
  "patient": 3,
  "reason": "Control anual"
}

### Pruebas de actualización

### Obtener ID creado
@attentionId = {{createAttention.response.body.id}}
//{{createAttention.response.body.id}}

### Actualización válida
PUT http://localhost:3000/api/attention/{{attentionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "date": "2025-12-01T10:00:00",
  "consultationHours": 1,
  "patient": 1,
  "result": "Todo normal",
  "reason": "Control anual completo"
}

### Actualización parcial
PATCH http://localhost:3000/api/attention/{{attentionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "observation": "Paciente llegó 15 minutos tarde"
}

### Cancelar atencion
PATCH http://localhost:3000/api/attention/{{attentionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dateCancelled": "2025-04-25"
}