  ### Crear un nuevo Secretario
# @name createtsecretary
POST http://localhost:3000/api/Secretaries
Content-Type: application/json

{
  "dni": "12345698",
  "firstname": "jose",
  "lastname": "Perecito",
  "username": "santino",
  "password": "santino",
  "dniType": "DNI",
  "mail": "juancito@santino.com",
  "bornDate": "1970-01-01"

}

### Obtener todos los Secretarios
GET http://localhost:3000/api/Secretaries

### ID obtenido de la respuesta de creación
@id = {{createtsecretary.response.body.data.id}}

### Obtener un Secretario por ID
GET http://localhost:3000/api/Secretaries/{{id}}

### Actualizar un Secretario (completo)
PUT http://localhost:3000/api/Secretaries/{{id}}
Content-Type: application/json

{
  "dni": "12345698",
  "firstname": "J",
  "lastname": "P",
  "username": "juanperezzz",
  "password": "123457",
  "dniType": "DNI",
  "mail": "juancito@perecito.com",
  "bornDate": "1970-01-01"
}

### Actualizar un Secretario (parcial)
PATCH http://localhost:3000/api/Secretaries/{{id}}
Content-Type: application/json

{
  "firstname": "Santino",
  "username": "santino",
  "password": "123458"
}

### Eliminar un Secretario
DELETE http://localhost:3000/api/Secretaries/{{id}}