### Crear un nuevo Secretario
# @name createSecretary
POST http://localhost:3000/api/Secretaries
Content-Type: application/json

{
  "dni": 12345678,
  "firstname": "Juancito",
  "lastname": "Perecito",
  "Username": "juanperezzz",
  "Password": "123457"
}


### ID obtenido de la respuesta de creación

@id = {createSecretary.response.body.data.id}



### Obtener todos los Secretarios
GET http://localhost:3000/api/Secretaries


### Obtener un Secretario por ID
GET http://localhost:3000/api/Secretaries/{{id}}

### Actualizar un Secretario (completo)
PUT http://localhost:3000/api/Secretaries/{{id}}
Content-Type: application/json

{
  "dni": 12345676,
  "firstname": "Jose",
  "lastname": "Jimenez",
  "Username": "josejimenez",
  "Password": "123457"
}

### Actualizar un Secretario (parcial)
PATCH http://localhost:3000/api/Secretaries/{{id}}
Content-Type: application/json

{
  "Username": "josecito",
  "Password": "123458"
}

### Eliminar un Secretario
DELETE http://localhost:3000/api/Secretaries/{{id}}