### Crear un nuevo Secretario
# @name createtsecretary
POST http://localhost:3000/api/Secretaries
Content-Type: application/json

{
  "dni": "12345698",
  "firstname": "Juancito",
  "lastname": "Perecito",
  "Username": "juanperezzz",
  "Password": "123457"
}

### Obtener todos los Secretarios
GET http://localhost:3000/api/Secretaries

### ID obtenido de la respuesta de creación
@id = {{createtsecretary.response.body.data.id}}

### Obtener un Secretario por ID
GET http://localhost:3000/api/Secretaries/{{id}}

### Actualizar un Secretario (completo)
PUT http://localhost:3000/api/Secretaries/{{id}}
Content-Type: application/json

{
  "dni": "12345676",
  "firstname": "Josecinho",
  "lastname": "Jimenez",
  "Username": "josejimenez",
  "Password": "123457"
}

### Actualizar un Secretario (parcial)
PATCH http://localhost:3000/api/Secretaries/{{id}}
Content-Type: application/json

{
  "Username": "josecito",
  "Password": "123458"
}

### Eliminar un Secretario
DELETE http://localhost:3000/api/Secretaries/{{id}}