### Con F12 en la web aparece el token de autenticación, copiar y asginar a la variable authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzYW50aW5vIiwicm9sZSI6InNlY3JldGFyeSIsImlhdCI6MTc0NTUyNTgzOCwiZXhwIjoxNzQ1NTI5NDM4fQ.I_GqX8whhUPKpY6ZBghBUWVsXOo3HJQxIhDR9gzMs0c

### 2. VALIDACIONES BÁSICAS
### 2.1 Campos obligatorios faltantes
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678"
}


### 2.2 Tipo DNI inválido
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "INVALIDO",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123"
}


### 2.3 Password corta
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "123"
}


### 3. VALIDACIONES DE UNICIDAD
### 3.1 Creación válida
# @name createMedic
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123",
  "specialty": 1
}

### 3.2 Username duplicado (deberia fallar)
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "87654321",
  "dniType": "DNI",
  "firstname": "Otro",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123"
}

### 4. ACTUALIZACIONES
@medicId = {{createMedic.response.body.data.id}}

### 4.1 Actualización con DNI existente (deberia fallar)
PUT http://localhost:3000/api/medics/{{medicId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "11111111",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico2",
  "password": "Password123"
}
