### Con F12 en la web aparece el token de autenticación, copiar y asginar a la variable authToken
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzYW50aW5vIiwicm9sZSI6InNlY3JldGFyeSIsImlhdCI6MTc0NTYwNjI5MiwiZXhwIjoxNzQ1NjA5ODkyfQ.UT5bzv8dpl2yHUJ0hh-YmKTYw_BNe0xNFaqkaLWGbWE

### VALIDACIONES BÁSICAS
### Campos obligatorios faltantes
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678"
}


### Tipo DNI inválido
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "INVALIDO",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123"
}


### Password corta
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "123"
}

### Espiacialidad inválida
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123",
  "specialty": 1250000
}

### VALIDACIONES DE UNICIDAD
### Creación válida
# @name createMedic
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "12345678",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123",
  "specialty": 1
}

### Username duplicado (deberia fallar)
POST http://localhost:3000/api/medics
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "87654321",
  "dniType": "DNI",
  "firstname": "Otro",
  "lastname": "Médico",
  "username": "cmedico",
  "password": "Password123"
}

### ACTUALIZACIONES
@medicId = {{createMedic.response.body.data.id}}

### Actualización con DNI existente (deberia fallar) (si en dniType ponemos otro tipo de documento, no deberia fallar)
PUT http://localhost:3000/api/medics/{{medicId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "dni": "21317912",
  "dniType": "DNI",
  "firstname": "Carlos",
  "lastname": "Médico",
  "username": "cmedico2",
  "password": "Password123"
}
