
###OBTENER TODOS LOS MEDICOS
GET http://localhost:3000/api/Medics

###OBTENER UN MEDICO
GET http://localhost:3000/api/Medics/525425

###crear un NUEVO MEDICO
POST http://localhost:3000/api/Medics
Content-Type: application/json

{
    "name": "Jane",
    "surname": "Doe",
    "dni": 123451,
    "license": 258413213
}

### MODIFICAREMOS UN MEDICO 
PUT http://localhost:3000/api/Medics/525425
Content-Type: application/json

{
    "name": "Jack"
}

### MODIFICAREMOS UN MEDICO PARCIALMENTE (PATCH - recurso parcial)
PATCH  http://localhost:3000/api/Medics/525425
Content-Type: application/json

{
    "name": "Lucho"
}

### BORRAR UN MEDICO
DELETE http://localhost:3000/api/Medics/525425
