

###crear una nueva obra social
# @name createHealthInsurance
POST http://localhost:3000/api/HealthInsurances
Content-Type: application/json

{
    "name": "Sancor"
}

###OBTENER TODAS LAS OBRAS SOCIALES
GET http://localhost:3000/api/HealthInsurances


### OBTENER ID
@id = {{createHealthInsurance.response.body.id}}

###OBTENER UNA OBRA SOCIAL
GET http://localhost:3000/api/HealthInsurances/{{id}}


### MODIFICAREMOS UNA OBRA SOCIAL 
PUT http://localhost:3000/api/HealthInsurances/{{id}}
Content-Type: application/json

{
    "name": "PAMIia"
}
### MODIFICAR OBRA SOCIAL (PATCH - recurso parcial)
PATCH http://localhost:3000/api/HealthInsurances/{{id}}
Content-Type: application/json

{
  "name": "PAMIIA"
}
### BORRAR UNA OBRA SOCIAL
DELETE http://localhost:3000/api/HealthInsurances/{{id}}
