
###OBTENER TODAS LAS OBRAS SOCIALES
GET http://localhost:3000/api/HealthInsurances

###OBTENER UNA OBRA SOCIAL
GET http://localhost:3000/api/HealthInsurances/2

###crear una nueva obra social
POST http://localhost:3000/api/HealthInsurances
Content-Type: application/json

{
    "name": "OSDE",
    "Patients": []
}

### MODIFICAREMOS UNA OBRA SOCIAL 
PUT http://localhost:3000/api/HealthInsurances/1
Content-Type: application/json

{
    "name": "PAMI",
    "Patients": []
}
### MODIFICAR OBRA SOCIAL (PATCH - recurso parcial)
PATCH http://localhost:3000/api/HealthInsurances/1
Content-Type: application/json

{
  "name": "PAMII"
}
### BORRAR UNA OBRA SOCIAL
DELETE http://localhost:3000/api/HealthInsurances/12
